language: c

matrix:
 include:
    - os: osx
      compiler: clang
      osx_image: xcode7.3
    - os: linux
      dist: trusty
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then rvm install 2.3 && rvm use 2.3 && ruby -v; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --assume-yes --quiet gcc-multilib; fi
install:
  - gem install rspec
  - gem install rubocop -v 0.57.2
script:
  - cd test && rake ci
